// Mocks generated by Mockito 5.4.5 from annotations
// in heunets_app/test/features/jobs/presentation/bloc/jobs_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:heunets_app/features/jobs/data/model/job_model.dart' as _i5;
import 'package:heunets_app/features/jobs/domain/repository/jobs_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JobsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobsRepository extends _i1.Mock implements _i2.JobsRepository {
  MockJobsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createJob({
    required String? companyName,
    required String? jobImagePath,
    required String? jobName,
    required String? jobTitle,
    required String? jobDescription,
    required String? category,
    required String? location,
    required double? amount,
    required List<String>? prerequisites,
    required List<String>? skillsNeeded,
    required DateTime? applicationDeadline,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createJob, [], {
              #companyName: companyName,
              #jobImagePath: jobImagePath,
              #jobName: jobName,
              #jobTitle: jobTitle,
              #jobDescription: jobDescription,
              #category: category,
              #location: location,
              #amount: amount,
              #prerequisites: prerequisites,
              #skillsNeeded: skillsNeeded,
              #applicationDeadline: applicationDeadline,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#createJob, [], {
                  #companyName: companyName,
                  #jobImagePath: jobImagePath,
                  #jobName: jobName,
                  #jobTitle: jobTitle,
                  #jobDescription: jobDescription,
                  #category: category,
                  #location: location,
                  #amount: amount,
                  #prerequisites: prerequisites,
                  #skillsNeeded: skillsNeeded,
                  #applicationDeadline: applicationDeadline,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i5.Job>> getJobs() =>
      (super.noSuchMethod(
            Invocation.method(#getJobs, []),
            returnValue: _i3.Future<List<_i5.Job>>.value(<_i5.Job>[]),
          )
          as _i3.Future<List<_i5.Job>>);

  @override
  _i3.Future<_i5.Job?> getJobById(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobById, [jobId]),
            returnValue: _i3.Future<_i5.Job?>.value(),
          )
          as _i3.Future<_i5.Job?>);

  @override
  _i3.Future<List<_i5.Job>> getJobsByEmployer(String? employerId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobsByEmployer, [employerId]),
            returnValue: _i3.Future<List<_i5.Job>>.value(<_i5.Job>[]),
          )
          as _i3.Future<List<_i5.Job>>);
}
